name: Test CRA
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get rep code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test application
        run: npm run test
        
