name: Test CRA
on: commit_comment
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get rep code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
        
